core/urls.py
from django.urls import path
from . import views

app_name = "core"


urlpatterns = [
    path("signup/",view=views.register_page,name="signup-page"),
    path("login/",view=views.login_page,name="login-page"),
    path("logout/",view=views.logout_user,name="logout-page"),

]

hirehub/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("jobmanager.urls",namespace='jobmanager'),),
    path("",include("subscribe.urls",namespace="subscribe")),
    path("",include("core.urls",namespace='core'),),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jobmanager/urls.py
from django.urls import path
from jobmanager import views

app_name = 'jobmanager'
urlpatterns = [
    path("",view=views.home_page,name="home-page"),
    path("jobs/<int:id>",view=views.job_detail,name="job-detail"),
    path("jobs/<int:id>/application/",view=views.job_application,name="job-application"),
    path("authors/<int:id>/",views.view_posted_jobs,name="posted-jobs"),
    path("authors/<int:id>/jobposts/",views.job_post,name="job-post"),
    path("profiles/<int:id>/",views.profile,name="profile-page"),
    path("jobpost/<int:id>/applications",views.view_applications,name="applications-list"),
    path("applications/<int:id>/",views.application_detail,name="application-detail"),
    path("authors/",views.author,name="author-page"),
    path('authors/<int:id>/jobpost/<int:jobpost_id>/', views.delete_job_post, name='delete-job-post'),
]

subscribe/urls.py
from django.urls import path
from . import views

app_name = "subscribe"
urlpatterns = [
    path("subscribe/",view=views.subscribe,name="subscribe"),
]

jobmanager/models.py
from typing import Iterable
from django.db import models
from django.utils.text import slugify
from django.conf import settings

class Author(models.Model):
    user = models.OneToOneField(to=settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=True)
    company = models.CharField(max_length=255)
    designation = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f'{self.user.first_name} {self.user.last_name}'
    
class Skills(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name 
# Create your models here.
class JobPost(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(null=True,blank=True,max_length=40)
    description = models.CharField(max_length=255)
    skills = models.ManyToManyField(to=Skills)
    location = models.ForeignKey(to='Location',on_delete=models.CASCADE,null=True)
    date = models.DateTimeField(auto_now_add=True)
    salary = models.IntegerField()
    application_deadline = models.DateField(null=True,blank=True)
    author = models.ForeignKey(to=Author,on_delete=models.CASCADE,null=True)


    def __str__(self) -> str:
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.id:
            base_slug = slugify(self.title)
            unique_suffix = self.author.company
            self.slug = f"{base_slug}-{slugify(unique_suffix)}-{slugify(self.location.city)}"
        return super().save(*args, **kwargs)  
    

class Location(models.Model):
    #street,city,state,country,zipcode
    street = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f'{self.city} - {self.state}'


class JobApplication(models.Model):
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    job_post = models.ForeignKey(to=JobPost,on_delete=models.CASCADE,related_name="applications")
    education = models.TextField()
    skills = models.ManyToManyField(to=Skills)
    available_to_start = models.DateField(null=True)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    resume = models.FileField(upload_to="jobmanager/applications")
    
    

jobmanager/forms.py
from django import forms
from .models import Author, JobPost,Location

class JobPostForm(forms.ModelForm):
    city = forms.CharField(max_length=255,widget=forms.TextInput(attrs={'placeholder':'Enter the city'}))
    state = forms.CharField(max_length=255,widget=forms.TextInput(attrs={'placeholder':'Enter the state'}))
    country = forms.CharField(max_length=255,widget=forms.TextInput(attrs={'placeholder':'Enter the country'}))
    zipcode = forms.CharField(max_length=10,widget=forms.TextInput(attrs={'placeholder':'Enter the zipcode'}))
    skills = forms.CharField(
        label='Skills',
        widget=forms.Textarea(attrs={'rows': 4, 'placeholder': 'Enter skills separated by commas'}),
        required=False  # Not required because we will handle validation manually
    )

    class Meta:
        model = JobPost
        fields = ['title', 'description', 'skills', 'salary', 'application_deadline']

        widgets = {
                'title':forms.TextInput(attrs={'placeholder': 'Enter job title'}),
                'description': forms.TextInput(attrs={'placeholder': 'Enter description'}),
                'application_deadline':forms.DateInput(attrs={'placeholder': 'Give an application deadline'}),
                'salary':forms.NumberInput(attrs={'placeholder': 'Enter the salary'})
            }


class AuthorForm(forms.ModelForm):
    name = forms.CharField(max_length=255)
    class Meta:
        model = Author
        fields = ["name","company","designation"]

        widgets = {
            'company':forms.TextInput(attrs={'class':'form-control','placeholder':'Current Working Compnay'}),
            'designation':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your designation'})
        }

jobmanager/views.py
from datetime import datetime
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, render,HttpResponse,redirect
from jobmanager.forms import AuthorForm, JobPostForm
from jobmanager.models import JobPost,JobApplication,Skills,Author,Location
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def home_page(request):
    jobs = JobPost.objects.order_by('-date')
    author = None
    if request.user.is_authenticated:
        author = Author.objects.filter(user=request.user).first()
    if request.method == "POST":
        keyword = request.POST.get("search-keywords")
        jobs = JobPost.objects.select_related("location").filter(location__city__icontains=keyword).all()
        if not jobs.exists():
            jobs = JobPost.objects.filter(title__icontains=keyword)
        return render(request, 'jobmanager/job-list.html', {'jobs': jobs, 'search_keyword': keyword, 'author': author})
    #pagination logic
    jobs = pagination_feature(queryset=jobs,request_obj=request)
    return render(request, 'jobmanager/job-list.html', {'jobs': jobs,'request':request,'author':author})

def pagination_feature(queryset,request_obj):
    paginator = Paginator(queryset,12)  # Show 10 items per page

    page = request_obj.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        items = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver last page of results.
        items = paginator.page(paginator.num_pages)
    return items



def job_list(request):
    if request.method == "GET":
        queryset = JobPost.objects.all().order_by("-date")
        return render(request=request,template_name="jobmanager/job-list.html",context={"jobs":queryset})

def job_detail(request,id):
    if request.method == "GET":
        job = JobPost.objects.prefetch_related("skills").get(id=id)
        skills = job.skills.all()
        return render(request,template_name="jobmanager/job-detail.html",context={'job':job,'skills':skills})
    
@login_required(login_url="core:login-page")
def job_application(request,id):
    application_exists = JobApplication.objects.filter(job_post__id=id,user=request.user).exists()
    if not application_exists:
        if request.method=="POST":
            skills_data = request.POST.get("skills").split(",")
            skills = [Skills.objects.get_or_create(name=name.strip())[0] for name in skills_data]
            job_application = get_application_data(request_obj=request,id=id)
            job_application.skills.set(skills)
            messages.success(request,"We submited your application")
            return redirect("jobmanager:job-detail",id=id)
        return render(request,"jobmanager/create-application.html",{'user':request.user})
    else:
        return HttpResponse("<h1>You have already submitted your form. Go Back</h1>")


def get_application_data(request_obj,id):
    education = request_obj.POST.get('education')
    available_to_start_str = request_obj.POST.get('available_to_start')
    available_to_start = datetime.strptime(available_to_start_str, '%m-%d-%Y').date()
    job_post = JobPost.objects.get(id=id)
    resume_file = request_obj.FILES.get('resume')
    print(resume_file)
    # Create JobApplication object
    job_application = JobApplication(
            user=request_obj.user,
            job_post=job_post,
            education=education,
            available_to_start=available_to_start,
            city=request_obj.POST.get('city'),
            state=request_obj.POST.get('state'),
            country=request_obj.POST.get('country'),
            resume = resume_file
        )
    job_application.save()
    print(job_application)
    return job_application


@login_required(login_url="core:login-page")
def job_post(request,id):
    author = Author.objects.filter(pk=id).first()
    if request.method == 'POST':
        form = JobPostForm(request.POST)
        if form.is_valid():
            skills_data = request.POST.get("skills").split(",")
            skills = [Skills.objects.get_or_create(name=name.strip())[0] for name in skills_data]
            location = get_location(request_obj=request)
            
            job_post = form.save(commit=False)
            job_post.author = author
            job_post.company = author.company
            job_post.location = location
            job_post.save()
            job_post.skills.set(skills)
            messages.success(request,f'The job post was successfully created')
            return redirect('jobmanager:posted-jobs',id=author.id)  
    form = JobPostForm()
    return render(request, 'jobmanager/create-jobpost.html', {'form': form})

def get_location(request_obj):
     city = request_obj.POST.get("city")
     state = request_obj.POST.get("state")
     country = request_obj.POST.get("country")
     zipcode = request_obj.POST.get("zipcode")
            
     # Create or get Location object
     location, created = Location.objects.get_or_create(
     city=city,
     state=state,
     country=country,
     zipcode=zipcode
            )
     return location

@login_required(login_url="core:login-page")
def profile(request,id):
    author = Author.objects.filter(user=request.user).first()
    user = request.user
    if request.method == "POST":
        user_form_data = {
            'first_name': request.POST.get("first_name"),
            'last_name': request.POST.get("last_name"),
            'username': request.POST.get("username"),
        }
        for key, value in user_form_data.items():
            setattr(user, key, value)
        
        user.save()

        if author is not None:
            author_form_data = {
                'company': request.POST.get("company"),
                'designation': request.POST.get("designation"),
            }

            for key, value in author_form_data.items():
                setattr(author, key, value)
            
            author.save()
        messages.success(request,"your profile is updated")
        return redirect('jobmanager:profile-page', id=id)  
    
    return render(request,"jobmanager/profile.html",{'user':request.user,'author':author})

@login_required(login_url="core:login-page")
def view_posted_jobs(request,id):
    author = Author.objects.get(id=id)
    job_posts = JobPost.objects.filter(author=author).order_by("-date")
    return render(request,"jobmanager/posted-jobs.html",{'posts':job_posts,'author':author})

@login_required(login_url="core:login-page")
def view_applications(request,id):
    job_post = JobPost.objects.get(id=id)
    applications = JobApplication.objects.filter(job_post=job_post)
    author = Author.objects.get(user=request.user)
    return render(request,"jobmanager/applications-list.html",{"applications":applications,"author":author})

@login_required(login_url="core:login-page")
def application_detail(request,id):
    job_application = JobApplication.objects.get(id=id)
    skills = job_application.skills.all()
    return render(request,"jobmanager/application-detail.html",{'application':job_application,"skills":skills})

@login_required(login_url="core:login-page")
def author(request):
    is_author = Author.objects.filter(user=request.user).exists()
    if not is_author:
        form = AuthorForm()
        if request.method == "POST":
            form = AuthorForm(request.POST)
            if form.is_valid():
                author = form.save(commit=False)
                author.user = request.user
                author.save()
                messages.success(request,"You now have access to post a job")
                return redirect("jobmanager:job-post",id=author.id)
        return render(request,"jobmanager/author.html",{'form':form})
    else:
        return redirect("/")
    

@login_required(login_url="core:login-page")
def delete_job_post(request, id,jobpost_id):
    job_post = get_object_or_404(JobPost,id=jobpost_id)
    # Check if the logged-in user has permission to delete the job application
    if request.user == job_post.author.user:
        job_post.delete()
        messages.success(request,"The job post was deleted")
        # Optionally, redirect to a success URL or another appropriate page
        return redirect('jobmanager:posted-jobs',id=id)
    return HttpResponseForbidden("You do not have permission to delete this job application.")

jobmanager/templates/jobmanager/application-detail.html
{% extends "jobmanager/nav-bar.html" %}
{%block title %}
<title>Application Detail</title>
{%endblock%}
    {% block content %}
    <h1>Applied by {{application.user.first_name}}</h1>
    <div class="card" style="width: 25rem; margin: 10px; padding:10px">
      <h5 class="card-title">{{application.user.first_name}} {{application.user.last_name}}</h5>
      <div class="card-body">{{application.education}}</div>
      <p class="card-text">{{application.city}}</p>
      <p class="card-text">{{application.state}}</p>
      <p class="card-text">Skills:</p>
      <ul>
        {% for skill in skills %}
        <li>{{ skill.name }}</li>
        {% endfor %}
      </ul>
      <p class="card-text"><a href="/media/{{application.resume}}" target="_blank">Resume</a></p>
    </div>
    {%endblock%}
  

jobmanager/templates/jobmanager/applications-list.html
{% extends "jobmanager/nav-bar.html" %}
{%block title %}
<title>Applications List</title>
{%endblock%}
{% block content %}
<div>
      <h3>The Job is posted by {{author.user.first_name}}</h3>
      <table class="table position-absolute">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Full Name</th>
            <th scope="col">Available To Start</th>
            <th scope="col">City</th>
            <th scope="col">All Details</th>
          </tr>
        </thead>
        <tbody>
          {% for application in applications%}
          <tr>
            <th scope="row">{{application.user.first_name}} {{application.user.last_name}}</th>
            <td>{{application.available_to_start}}</td>
            <td>{{application.city}}</td>
            <td>
              <a
                style="text-decoration: none;"
                href="{% url 'jobmanager:application-detail' id=application.id%}"
                <button
                  type="button"
                  class="btn btn-info"
                >
                  Details
                </button>
                </a
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock %}

jobmanager/templates/jobmanager/author.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Author Details</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static "css/update-profile.css" %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  
    </head>
    <body>
        <div class="container rounded bg-white mt-5 mb-5">
            <div class="row">
                <div class="col-md-3 border-right">
                    <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg"><span class="font-weight-bold">{{user.first_name}}</span><span class="text-black-50">{{user.email}}</span><span> </span></div>
                </div>
                <div class="col-md-5 border-right">
                    <div class="p-3 py-5">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right">Author Settings</h4>
                            <a href="{% url 'jobmanager:home-page'%}" >Home</a>
                        </div>
                        <form method="post">
                            {% csrf_token %}
                        <div class="row mt-2">
                            <div class="col-md-6"><label class="labels fs-6">Name</label>
                                <input type="text" class="form-control" placeholder="Enter your firstname" value="{{user.first_name}} {{user.last_name}}" name="name" >
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-md-6"><label class="labels fs-6">Company</label>{{form.company}}</div>
                            <div class="col-md-6"><label class="labels fs-6">Designation</label>{{form.designation}}</div>
                        </div>
                        <div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="submit">Save Profile</button></div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
        </div>
        </div>
        {% for message in messages %}
            <p class="text-success link-underline-success">{{message}}</p>
        {% endfor %}
        <script src="" async defer></script>
    </body>
</html>


{% comment %} <div class="row mt-2">
    <div class="col-md-6"><label class="labels">Name</label>{{form.user}}</div>
    <div class="col-md-6"><label class="labels">Company</label>{{form.company}}</div>
    <div class="col-md-6"><label class="labels">Designation</label>{{form.designation}}</div>
</div> {% endcomment %}

jobmanager/templates/jobmanager/job-detail.html
{% extends "jobmanager/nav-bar.html" %}
{%block title %}
<title>Job Details Page</title>
{%endblock%}
    {% block content %}
    {% for message in messages %}
<p class="text-success link-underline-success">{{message}}</p>
{% endfor %}
    <div class="d-flex flex-column justify-content-center align-items-center">
    <h1>Job Details page</h1>
    <div class="card" style="width: 18rem; padding:10px">
      <div class="card-body p-2"></div>
      <h5 class="card-title">{{job.title}}</h5>
      <h6 class="card-subtitle mb-2 text-muted">{{job.company}}</h6>
      <p class="card-text">{{job.description}}</p>
      <p class="card-text">{{job.location}}</p>
      <p class="card-text">Requirements:</p>
      <ul>
        {% for skill in skills %}
        <li>{{ skill.name }}</li>
        {% endfor %}
      </ul>
    </div>
    {% if user.is_authenticated %}
        <a class="btn btn-primary m-3" href="{% url 'jobmanager:job-application' id=job.id %}">Apply</a>
    {% else %}
        <a class="btn btn-primary m-3" href="{% url 'core:login-page' %}?next={% url 'jobmanager:job-application' id=job.id %}">Apply</a>
    {% endif %}
  </div>
  
    {%endblock%}
  

jobmanager/templates/jobmanager/nav-bar.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    {% block title %}
    <title>Job List</title>
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body class="overflow-x-hidden">
       
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">HireHub</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'jobmanager:home-page' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:login-page'%}">Login</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Profile
                </a>
              
              <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'jobmanager:profile-page' id=user.id %}">View Profile</a></li>
                {% if author %}
                  <li><a class="dropdown-item" href="{% url 'jobmanager:posted-jobs' id=author.id %}">Posted Jobs</a></li>
                {% endif %}
                <li><a class="dropdown-item" href="{%url 'core:logout-page' %}">Logout</a></li>
                <li><hr class="dropdown-divider"></li>
              </ul>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" aria-disabled="true" href="{%url 'core:signup-page'%}">Signup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-disabled="true" href="{%url 'subscribe:subscribe'%}">Subscribe to Newsletter</a>
            </li>
            {% if not author and request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" aria-disabled="true" href="{%url 'jobmanager:author-page'%}">Post a Job</a>
                </li>
                {% endif %}
          </ul>
          {% if request.user.is_authenticated %}
              <p class="fw-bold fw-bolder m-3">Welcome {{request.user.first_name}}</p>
          {% endif %}
          <form class="d-flex" role="search" method="post">
            {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Search by city and title" name="search-keywords" aria-label="Search" value={{search_keyword}}>
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
      {% block content %}
       {% endblock %}
  </body>
</html>

jobmanager/templates/jobmanager/posted-jobs.html
{% extends "jobmanager/nav-bar.html" %}
{% block title %}
<title>Posted Jobs List</title>
{% endblock%}
{% block content %}
<div>
      <h3 class="d-inline">Jobs Posted by {{author.user.first_name}}</h3>
      <a type="button" class="btn btn-primary m-2" href="{%url 'jobmanager:job-post' id=author.id%}">Create</a>
      <table class="table position-absolute">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Company</th>
            <th scope="col">Location</th>
            <th scope="col">View</th>
          </tr>
        </thead>
        <tbody>
          {% for job in posts%}
          <tr>
            <th scope="row">{{job.title}}</th>
            <td>{{job.author.company}}</td>
            <td>{{job.location}}</td>
            <td>
              <a
                style="text-decoration: none;"
                href="{% url 'jobmanager:applications-list' id=job.id %}"
                target="_blank"
                <button
                  type="button"
                  class="btn btn-info"
                >
                  View
                </button>
              </a>
              <a href="{% url 'jobmanager:delete-job-post' id=author.id jobpost_id=job.id %}">
                <button type="button" class="btn btn-danger">Delete</button>
            </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% for message in messages %}
      <p class="text-success link-underline-success">{{message}}</p>
    {% endfor %}
{% endblock %}

jobmanager/templates/jobmanager/profile.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Profile Settings</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static "css/update-profile.css" %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  
    </head>
    <body>
        <div class="container rounded bg-white mt-5 mb-5">
            <div class="row">
                <div class="col-md-3 border-right">
                    <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg"><span class="font-weight-bold">{{user.first_name}}</span><span class="text-black-50">{{user.email}}</span><span> </span></div>
                </div>
                <div class="col-md-5 border-right">
                    <div class="p-3 py-5">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right">Profile Settings</h4>
                            <a href="{% url 'jobmanager:home-page'%}" >Home</a>
                        </div>
                        <form method="post">
                            {% csrf_token %}
                        <div class="row mt-2">
                            <div class="col-md-6"><label class="labels">First Name</label><input type="text" class="form-control" placeholder="Enter your firstname" value="{{user.first_name}}" name="first_name" ></div>
                            <div class="col-md-6"><label class="labels">Last Name</label><input type="text" class="form-control" value="{{user.last_name}}" placeholder="Enter your Last Name" name="last_name"></div>
                            <div class="col-md-6"><label class="labels">Username</label><input type="text" class="form-control" value="{{user.username}}" placeholder="Username" name="username"></div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-md-12"><label class="labels">Email</label><input type="email" class="form-control" placeholder="enter your email id" name="email" value="{{user.email}}" disabled></div>
                        </div>
                        {% if author %}
                        <div class="row mt-3">
                            <div class="col-md-6"><label class="labels">Current Working Company</label><input type="text" class="form-control" name="company" value="{{author.company}}"></div>
                            <div class="col-md-6"><label class="labels">Designation</label><input type="text" class="form-control" name="designation" value="{{author.designation}}"></div>
                        </div>
                        {% endif %}
                        <div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="submit">Save Profile</button></div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
        </div>
        </div>
        {% for message in messages %}
            <p class="text-success link-underline-success">{{message}}</p>
        {% endfor %}
        <script src="" async defer></script>
    </body>
</html>